#!/bin/bash

VERSION=$(panrec --version)
ghr -t ${GITHUB_TOKEN} \
    -u ${CIRCLE_PROJECT_USERNAME} \
    -r ${CIRCLE_PROJECT_REPONAME} \
    -c ${CIRCLE_SHA1} \
    -delete ${VERSION} \
    $HOME/.local/bin