name: Haskell CI

on:
  push:
    branches:
    - master
    - develop
    - feature/*
  pull_request:
    branches:
    - develop

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: set allow-newer for stack
      run: 'mkdir -p $HOME/.stack && echo "allow-newer: true" >> $HOME/.stack/config.yaml'
    - name: Build
      run: stack build
    - name: Run tests
      run: stack test
